name: Deploy to GitHub Pages 2.0

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
    - name: Build WASM to node_modules
      run: wasm-pack build --target bundler --out-dir ./frontend/node_modules/black-scholes
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install and Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: Move build to root
      run: |
        mv frontend/dist ./dist
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist